#!/usr/bin/env node

/**
 * Build Styles Script
 *
 * Bundles all CSS files (tokens + components) into dist/styles for package distribution.
 * Concatenates CSS directly instead of using @import (better compatibility with npm link).
 */

const fs = require('fs');
const path = require('path');
const { glob } = require('glob');

const ROOT_DIR = path.resolve(__dirname, '..');
const DIST_DIR = path.join(ROOT_DIR, 'dist');
const DIST_STYLES_DIR = path.join(DIST_DIR, 'styles');
const STYLES_DIR = path.join(ROOT_DIR, 'styles');
const COMPONENTS_DIR = path.join(ROOT_DIR, 'components');

/**
 * Read and return file contents
 */
function readCSS(filePath) {
  return fs.readFileSync(filePath, 'utf-8');
}

async function buildStyles() {
  console.log('Building styles...');

  // Ensure dist/styles directory exists
  if (!fs.existsSync(DIST_STYLES_DIR)) {
    fs.mkdirSync(DIST_STYLES_DIR, { recursive: true });
  }

  // Copy token CSS files from styles/
  const tokenFiles = await glob('*.css', { cwd: STYLES_DIR });
  for (const file of tokenFiles) {
    const src = path.join(STYLES_DIR, file);
    const dest = path.join(DIST_STYLES_DIR, file);
    fs.copyFileSync(src, dest);
    console.log(`  Copied: styles/${file}`);
  }

  // Create components subdirectory in dist/styles
  const componentsStylesDir = path.join(DIST_STYLES_DIR, 'components');
  if (!fs.existsSync(componentsStylesDir)) {
    fs.mkdirSync(componentsStylesDir, { recursive: true });
  }

  // Copy component CSS files to dist/styles/components and dist/esm/cjs
  const componentCssFiles = await glob('*/*.css', { cwd: COMPONENTS_DIR });
  const componentNames = [];

  for (const file of componentCssFiles) {
    const src = path.join(COMPONENTS_DIR, file);
    const componentName = path.dirname(file);
    const cssFileName = path.basename(file);

    // Copy to dist/styles/components/
    const dest = path.join(componentsStylesDir, `${componentName}.css`);
    fs.copyFileSync(src, dest);
    componentNames.push(componentName);
    console.log(`  Copied: components/${file} -> dist/styles/components/${componentName}.css`);

    // Also copy CSS files next to compiled JS for bundler compatibility
    const esmComponentDir = path.join(DIST_DIR, 'esm', 'components', componentName);
    const cjsComponentDir = path.join(DIST_DIR, 'cjs', 'components', componentName);

    if (fs.existsSync(esmComponentDir)) {
      fs.copyFileSync(src, path.join(esmComponentDir, cssFileName));
      console.log(`  Copied: components/${file} -> dist/esm/components/${componentName}/${cssFileName}`);
    }

    if (fs.existsSync(cjsComponentDir)) {
      fs.copyFileSync(src, path.join(cjsComponentDir, cssFileName));
      console.log(`  Copied: components/${file} -> dist/cjs/components/${componentName}/${cssFileName}`);
    }
  }

  // Read base CSS
  const baseCSS = readCSS(path.join(STYLES_DIR, 'base.css'));

  // Read component CSS files
  const componentCSS = componentNames
    .map(name => {
      const cssPath = path.join(componentsStylesDir, `${name}.css`);
      return `/* ${name} */\n${readCSS(cssPath)}`;
    })
    .join('\n\n');

  // Create bundled theme files (concatenated, no @import)
  const themes = ['muka-light', 'muka-dark', 'wireframe-light', 'wireframe-dark'];

  for (const theme of themes) {
    const tokenCSS = readCSS(path.join(STYLES_DIR, `tokens-${theme}.css`));

    const bundledCSS = `/* Muka UI - ${theme} theme (bundled) */
/* Generated by build-styles.js - DO NOT EDIT */

/* ========== Base Styles ========== */
${baseCSS}

/* ========== Theme Tokens ========== */
${tokenCSS}

/* ========== Component Styles ========== */
${componentCSS}
`;

    fs.writeFileSync(path.join(DIST_STYLES_DIR, `${theme}.css`), bundledCSS);
    console.log(`  Created: dist/styles/${theme}.css (bundled)`);
  }

  // Create main index.css (uses muka-light as default, bundled)
  const defaultTokenCSS = readCSS(path.join(STYLES_DIR, 'tokens-muka-light.css'));

  const indexCSS = `/* Muka UI - All Styles (bundled) */
/* Generated by build-styles.js - DO NOT EDIT */
/* Default theme: muka-light */

/* ========== Base Styles ========== */
${baseCSS}

/* ========== Theme Tokens (muka-light) ========== */
${defaultTokenCSS}

/* ========== Component Styles ========== */
${componentCSS}
`;

  fs.writeFileSync(path.join(DIST_STYLES_DIR, 'index.css'), indexCSS);
  console.log('  Created: dist/styles/index.css (bundled)');

  console.log('Styles build complete!');
}

buildStyles().catch(err => {
  console.error('Error building styles:', err);
  process.exit(1);
});
