/*
 * Autogenerated with Code Connect
 *
 * To update this file, install the Figma plugin and run the command:
 *   $ npm run figma:connect:publish
 *
 * https://www.figma.com/community/plugin/1558514408736757109
 */

import { registerComponent, figma } from "@figma/code-connect";
import { Button } from "../../components/Button";

registerComponent(Button, {
  figmaNode: figma.instance("Button"),
  example: (
    <Button
      variant={figma.enum("variant")}
      size={figma.enum("size")}
      disabled={figma.enum("disabled")}
      fullWidth={figma.boolean("fullWidth")}
    >
      {figma.string("Text")}
    </Button>
  ),
  props: {
    variant: figma.enum("variant"),
    size: figma.enum("size"),
    disabled: figma.enum("disabled"),
    fullWidth: figma.boolean("fullWidth"),
    children: figma.string("Text"),
    type: figma.enum("type"),
    iconOnly: figma.boolean("iconOnly"),
  },
});

