/*
 * Autogenerated with Code Connect
 *
 * To update this file, install the Figma plugin and run the command:
 *   $ npm run figma:connect:publish
 *
 * https://www.figma.com/community/plugin/1558514408736757109
 */

import { registerComponent, figma } from "@figma/code-connect";
import { Input } from "../../components/Input";

registerComponent(Input, {
  figmaNode: figma.instance("Input"),
  example: (
    <Input
      size={figma.enum("size")}
      disabled={figma.enum("disabled")}
      error={figma.enum("error")}
      fullWidth={figma.boolean("fullWidth")}
      placeholder={figma.string("Placeholder")}
      label={figma.string("Label")}
      helperText={figma.string("Helper Text")}
    />
  ),
  props: {
    size: figma.enum("size"),
    disabled: figma.enum("disabled"),
    error: figma.enum("error"),
    fullWidth: figma.boolean("fullWidth"),
    placeholder: figma.string("Placeholder"),
    label: figma.string("Label"),
    helperText: figma.string("Helper Text"),
    errorMessage: figma.string("Error Message"),
    type: figma.enum("type"),
    required: figma.boolean("required"),
    readOnly: figma.boolean("readOnly"),
  },
});
