/*
 * Autogenerated with Code Connect
 *
 * To update this file, install the Figma plugin and run the command:
 *   $ npm run figma:connect:publish
 *
 * https://www.figma.com/community/plugin/1558514408736757109
 */

import { registerComponent, figma } from "@figma/code-connect";
import { ListItem } from "../../components/ListItem";

registerComponent(ListItem, {
  figmaNode: figma.instance("List Item"),
  example: (
    <ListItem
      label={figma.string("Text")}
      caption={figma.string("Caption")}
      showChevron={figma.enum("chevron")}
      showDivider={figma.enum("divider")}
      disabled={figma.enum("disabled")}
      selected={figma.enum("selected")}
    />
  ),
  props: {
    label: figma.string("Text"),
    caption: figma.conditionalProp(
      figma.enum("caption"),
      figma.boolean(true)
    ).value(figma.string("Caption")),
    showChevron: figma.enum("chevron"),
    showDivider: figma.enum("divider"),
    disabled: figma.enum("disabled"),
    selected: figma.enum("selected"),
  },
});
