/*
 * Autogenerated with Code Connect
 *
 * To update this file, install the Figma plugin and run the command:
 *   $ npm run figma:connect:publish
 *
 * https://www.figma.com/community/plugin/1558514408736757109
 */

import { registerComponent, figma } from "@figma/code-connect";
import { Radio } from "../../components/Radio";

registerComponent(Radio, {
  figmaNode: figma.instance("Radio"),
  example: (
    <Radio
      size={figma.enum("size")}
      disabled={figma.enum("disabled")}
      checked={figma.enum("checked")}
      label={figma.string("Label")}
    />
  ),
  props: {
    size: figma.enum("size"),
    disabled: figma.enum("disabled"),
    checked: figma.enum("checked"),
    label: figma.string("Label"),
  },
});
